// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brpbuipvxvqyaislbfwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJycGJ1aXB2eHZxeWFpc2xiZnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyMDU5NDYsImV4cCI6MjA1MDc4MTk0Nn0.AmDVo3FjhUMTIp49IQLZFCzoUZWj5f8ylW_p6qTf_nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);